import {
  signOut,
  type User,
  GoogleAuthProvider,
  signInWithPopup,
} from "firebase/auth";
import { doc, getDoc } from "firebase/firestore";
import { auth, db } from "./firebase";
import { createMessage } from "../modules/utils";

/**
 * Signs out the user
 */
export async function signOutUser(): Promise<void> {
  try {
    await signOut(auth);
    const logOut = document.getElementById("logout");
    if (logOut) logOut.classList.add("hide");
    createMessage({messageBody: "You have been signed out", location: "main-message", type: "info"});
  } catch (error) {
    createMessage(
     { messageBody: `Error during user logout: ${error}`,
      location: "main-message",
      type: "error",}
    );
    throw error;
  }
}

/**
 * Get the user's info if they are signed in
 * @returns - The user's info
 */
export function getCurrentUser(): User | null {
  return auth.currentUser;
}

/**
 * Gets the user's role (if set) from the Firestore. User's are manually assigned roles in the
 * Firebase console
 * @param uid - The ID of the user, generated by Firebase
 * @returns - The user's role (if set)
 */
export async function getUserRole(uid: string): Promise<string | null> {
  const cacheKey = `user_role_${uid}`;
  const cachedRole = sessionStorage.getItem(cacheKey);
  if (cachedRole !== null) {
    return cachedRole;
  }
  const userDocRef = doc(db, "users", uid);
  try {
    const userDoc = await getDoc(userDocRef);
    if (userDoc.exists()) {
      const role = (userDoc.data()?.role as string) || null;
      if (role) {
        sessionStorage.setItem(cacheKey, role);
      }
      return role;
    } else {
      console.log("User role document not found for UID:", uid);
      return null;
    }
  } catch (error) {
    console.error("Error fetching user role from Firestore:", error);
    throw error;
  }
}

/**
 * Opens the sign in with Google screen in a new window
 * @returns - Returns the result of the sign in
 */
export async function signInWithGooglePopup() {
  //Create new instance of Google Auth Provider
  const provider = new GoogleAuthProvider();
  try {
    //Open the pop-up window and wait for the user to sign in
    const result = await signInWithPopup(auth, provider);
    // The signed-in user info is in the 'result.user'
    return result;
  } catch (error: any) {
    throw error;
  }
}

export function getAuthenticatedUser(): Promise<User | null> {
    return new Promise((resolve) => {
        const unsubscribe = auth.onAuthStateChanged((user) => {
            unsubscribe();
            resolve(user);
        });
    });
}

export type { User };
